# Generated by Django 6.0 on 2026-01-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vessel',
            options={'managed': False},
        ),
    ]
